site_name: MarkenX Wiki

nav:
  - Inicio: index.md
  - Documentaci√≥n:
      - Historias de Usuario: user-stories/stories/index.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.extra
  - pymdownx.tasklist
  - pymdownx.betterem
